import type { Event } from "@/lib/types";

export const MOCK_EVENTS: Event[] = [
  {
    id: "e1",
    title: "Bagong Pag-asa Barangay Cleanup Drive",
    date: "2026-04-12",
    time: "6:00 AM",
    location: "Bagong Pag-asa Barangay Hall",
    category: "Environment",
    attendees: 42,
    description: "Community cleanup along the main drainage canal. Gloves and bags provided.",
  },
  {
    id: "e2",
    title: "QC Tech Meetup: Smart Cities",
    date: "2026-04-15",
    time: "6:00 PM",
    location: "UP Technohub, Diliman",
    category: "Technology",
    attendees: 87,
    description: "Panel discussion on civic tech, open data, and urban innovation in Quezon City.",
  },
  {
    id: "e3",
    title: "Urban Gardening Workshop",
    date: "2026-04-19",
    time: "9:00 AM",
    location: "QC Memorial Circle",
    category: "Lifestyle",
    attendees: 31,
    description: "Learn container gardening and composting techniques for urban spaces.",
  },
  {
    id: "e4",
    title: "Flood Preparedness Forum",
    date: "2026-04-22",
    time: "2:00 PM",
    location: "Batasan Pambansa Complex",
    category: "Safety",
    attendees: 120,
    description: "MMDA and PAGASA present flood risk maps and evacuation routes for QC residents.",
  },
  {
    id: "e5",
    title: "QC Cycling Saturday",
    date: "2026-04-26",
    time: "5:30 AM",
    location: "Elliptical Road, QC Circle",
    category: "Sports",
    attendees: 65,
    description: "Weekly casual bike ride around QC Memorial Circle. All bikes welcome.",
  },
  {
    id: "e6",
    title: "Barangay Health Fair",
    date: "2026-04-28",
    time: "8:00 AM",
    location: "Fairview Community Center",
    category: "Health",
    attendees: 200,
    description: "Free blood pressure checks, dental consultations, and vaccination for QC residents.",
  },
  {
    id: "e7",
    title: "Indie Film Screening: QC Stories",
    date: "2026-05-03",
    time: "7:00 PM",
    location: "Cubao Expo",
    category: "Arts",
    attendees: 54,
    description: "Short film festival featuring stories set in Quezon City neighborhoods.",
  },
  {
    id: "e8",
    title: "Solid Waste Management Seminar",
    date: "2026-05-08",
    time: "10:00 AM",
    location: "QC City Hall, Session Hall",
    category: "Environment",
    attendees: 78,
    description: "Introduction to QC's new waste segregation policy and schedule for 2026.",
  },
];
