import type { Professional } from "@/lib/types";

export const MOCK_PROFESSIONALS: Professional[] = [
  {
    id: "p1",
    name: "Maria Santos",
    profession: "Urban Planner",
    barangay: "Diliman",
    bio: "Specializes in flood-resilient urban design and community-centered city planning.",
    initials: "MS",
    color: "#1E3A8A",
  },
  {
    id: "p2",
    name: "Juan dela Cruz",
    profession: "Environmental Scientist",
    barangay: "Fairview",
    bio: "Researches water quality and biodiversity in Quezon City's creek systems.",
    initials: "JD",
    color: "#16A34A",
  },
  {
    id: "p3",
    name: "Ana Reyes",
    profession: "Barangay Health Worker",
    barangay: "Batasan Hills",
    bio: "Public health advocate focused on sanitation and community wellness programs.",
    initials: "AR",
    color: "#DC2626",
  },
  {
    id: "p4",
    name: "Carlo Mendoza",
    profession: "Civil Engineer",
    barangay: "Project 6",
    bio: "Infrastructure specialist with experience in drainage system rehabilitation.",
    initials: "CM",
    color: "#D97706",
  },
  {
    id: "p5",
    name: "Sofia Lim",
    profession: "Data Scientist",
    barangay: "Cubao",
    bio: "Applies machine learning to civic datasets for traffic and flood prediction.",
    initials: "SL",
    color: "#2563EB",
  },
  {
    id: "p6",
    name: "Rico Villanueva",
    profession: "Community Organizer",
    barangay: "Commonwealth",
    bio: "Mobilizes residents for barangay initiatives, cleanup drives, and advocacy.",
    initials: "RV",
    color: "#1E1B4B",
  },
  {
    id: "p7",
    name: "Ligaya Cruz",
    profession: "Architect",
    barangay: "Novaliches",
    bio: "Designs affordable community spaces and public parks for underserved barangays.",
    initials: "LC",
    color: "#F59E0B",
  },
  {
    id: "p8",
    name: "Bernard Tan",
    profession: "Civic Tech Developer",
    barangay: "Tandang Sora",
    bio: "Builds open-source tools for LGU transparency and citizen participation.",
    initials: "BT",
    color: "#16A34A",
  },
];
