import type { Report } from "@/lib/types";

export const MOCK_REPORTS: Report[] = [
  {
    id: "r1",
    category: "flooding",
    title: "Street flooding after heavy rain",
    description: "Knee-deep floodwater blocking Batasan Road near the public market.",
    barangay: "Batasan Hills",
    district: 2,
    timestamp: "2026-04-06T07:30:00+08:00",
    upvotes: 34,
    status: "verified",
  },
  {
    id: "r2",
    category: "trash",
    title: "Illegal dumping near creek",
    description: "Large pile of household waste dumped along the Fairview creek bank.",
    barangay: "Fairview",
    district: 6,
    timestamp: "2026-04-06T06:15:00+08:00",
    upvotes: 18,
    status: "pending",
  },
  {
    id: "r3",
    category: "bad-driver",
    title: "Tricycle obstructing jeepney lane",
    description: "Multiple tricycles parking on the main road near Cubao MRT causing heavy traffic.",
    barangay: "Cubao",
    district: 4,
    timestamp: "2026-04-06T08:00:00+08:00",
    upvotes: 12,
    status: "pending",
  },
  {
    id: "r4",
    category: "flooding",
    title: "Flooded underpass",
    description: "Diliman underpass flooded — waist deep. Vehicles unable to pass.",
    barangay: "Diliman",
    district: 3,
    timestamp: "2026-04-05T18:45:00+08:00",
    upvotes: 61,
    status: "resolved",
  },
  {
    id: "r5",
    category: "biodiversity",
    title: "Philippine eagle-owl sighted",
    description: "Spotted a Philippine eagle-owl roosting in the UP Diliman campus trees.",
    barangay: "Diliman",
    district: 3,
    timestamp: "2026-04-05T17:20:00+08:00",
    upvotes: 45,
    status: "verified",
  },
  {
    id: "r6",
    category: "accident",
    title: "Motorcycle collision at intersection",
    description: "Two motorcycles collided at the corner of Tandang Sora and Visayas Ave.",
    barangay: "Tandang Sora",
    district: 6,
    timestamp: "2026-04-05T16:00:00+08:00",
    upvotes: 9,
    status: "resolved",
  },
  {
    id: "r7",
    category: "trash",
    title: "Overflowing garbage bins",
    description: "Community bins at Kamuning market haven't been collected in 4 days.",
    barangay: "Kamuning",
    district: 4,
    timestamp: "2026-04-05T14:30:00+08:00",
    upvotes: 27,
    status: "pending",
  },
  {
    id: "r8",
    category: "flooding",
    title: "Clogged drainage causing floods",
    description: "Drainage along Project 6 main road is clogged with leaves — floods every rain.",
    barangay: "Project 6",
    district: 5,
    timestamp: "2026-04-05T12:00:00+08:00",
    upvotes: 19,
    status: "verified",
  },
  {
    id: "r9",
    category: "biodiversity",
    title: "Stray cat colony needs feeding station",
    description: "Large colony of stray cats near Anonas station, no feeding station present.",
    barangay: "Anonas",
    district: 3,
    timestamp: "2026-04-04T10:00:00+08:00",
    upvotes: 33,
    status: "pending",
  },
  {
    id: "r10",
    category: "other",
    title: "Broken streetlight for 2 weeks",
    description: "Streetlight at the corner of Visayas Ave and EDSA has been broken for two weeks.",
    barangay: "Bagong Pag-asa",
    district: 5,
    timestamp: "2026-04-04T08:00:00+08:00",
    upvotes: 41,
    status: "verified",
  },
  {
    id: "r11",
    category: "bad-driver",
    title: "Bus counterflowing on main road",
    description: "P2P bus seen counterflowing on Commonwealth Ave near Ever Gotesco.",
    barangay: "Commonwealth",
    district: 6,
    timestamp: "2026-04-03T07:15:00+08:00",
    upvotes: 55,
    status: "resolved",
  },
  {
    id: "r12",
    category: "flooding",
    title: "Residential area flooded",
    description: "Several homes in Novaliches flooded — residents requesting immediate pumping assistance.",
    barangay: "Novaliches",
    district: 6,
    timestamp: "2026-04-03T06:00:00+08:00",
    upvotes: 72,
    status: "verified",
  },
];
